module OV7670_config_rom(
    input  wire        clk,
    input  wire [7:0]  addr,
    output logic [15:0] dout
);

always @(posedge clk) begin
    case (addr)
        //ROM GENERATED BY GPT
        // ---------------------------
        // RESET
        // ---------------------------
        0:  dout <= 16'h12_80;   // COM7   Reset
        1:  dout <= 16'hFF_F0;   // Delay

        // ---------------------------
        // BASIC MODE SETUP
        // ---------------------------
        2:  dout <= 16'h12_00;   // COM7   YUV, no RGB modes
        3:  dout <= 16'h11_00;   // CLKRC  No prescaling (use full XCLK)
        4:  dout <= 16'h0C_00;   // COM3   No scaling, no DCW
        5:  dout <= 16'h3E_00;   // COM14  Normal PCLK, no scaling
        6:  dout <= 16'h04_00;   // COM1   Disable CCIR656

        // ---------------------------
        // OUTPUT FORMAT
        // ---------------------------
        7:  dout <= 16'h40_00;   // COM15  Full output range, no RGB limits
        8:  dout <= 16'h3A_04;   // TSLB   Correct YUYV byte order

        // ---------------------------
        // GAIN / EXPOSURE (AUTO)
        // ---------------------------
        9:  dout <= 16'h13_E5;   // COM8   Enable AGC, AEC, AWB
        10: dout <= 16'h14_18;   // COM9   AGC gain ×4
        11: dout <= 16'hA5_05;   // BD50MAX
        12: dout <= 16'hAB_07;   // BD60MAX
        13: dout <= 16'h24_95;   // AGC upper limit
        14: dout <= 16'h25_33;   // AGC lower limit
        15: dout <= 16'h26_E3;   // AGC/AEC fast mode region

        // ---------------------------
        // VGA WINDOWING (CORRECT)
        // ---------------------------
        16: dout <= 16'h17_13;   // HSTART
        17: dout <= 16'h18_01;   // HSTOP
        18: dout <= 16'h32_6B;   // HREF
        19: dout <= 16'h19_02;   // VSTART
        20: dout <= 16'h1A_7A;   // VSTOP
        21: dout <= 16'h03_0A;   // VREF

        // ---------------------------
        // MISC
        // ---------------------------
        22: dout <= 16'h1E_00;   // MVFP  (no mirror/flip)
        23: dout <= 16'h69_00;   // GFIX  Gain fix

        // ---------------------------
        // END OF ROM
        // ---------------------------
        default: dout <= 16'hFF_FF;

    endcase
end

endmodule
