set_property -dict { PACKAGE_PIN N15 IOSTANDARD LVCMOS33 } [get_ports clk]
create_clock -period 10.000 -name clk [get_ports clk]

set_property -dict { PACKAGE_PIN F14 IOSTANDARD LVCMOS33 } [get_ports cam_vsync]
set_property -dict { PACKAGE_PIN F15 IOSTANDARD LVCMOS33 } [get_ports pclk]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets pclk_IBUF]

set_property -dict { PACKAGE_PIN H13 IOSTANDARD LVCMOS33 } [get_ports pwdn]
set_property -dict { PACKAGE_PIN J1 IOSTANDARD LVCMOS33 } [get_ports reset]
set_property -dict { PACKAGE_PIN J2 IOSTANDARD LVCMOS33 } [get_ports start_fsm]
set_property -dict { PACKAGE_PIN J13 IOSTANDARD LVCMOS33 } [get_ports scl]
set_property -dict { PACKAGE_PIN J14 IOSTANDARD LVCMOS33 } [get_ports sda]
set_property -dict { PACKAGE_PIN E14 IOSTANDARD LVCMOS33 } [get_ports xclk]
set_property -dict { PACKAGE_PIN E15 IOSTANDARD LVCMOS33 } [get_ports cam_href]

set_property -dict { PACKAGE_PIN H2 IOSTANDARD LVCMOS33 } [get_ports toggle_edge]
set_property -dict { PACKAGE_PIN G2 IOSTANDARD LVCMOS33 } [get_ports toggle_skin]



set_property -dict { PACKAGE_PIN H18 IOSTANDARD LVCMOS33 } [get_ports {cam_data[3]}]
set_property -dict { PACKAGE_PIN G18 IOSTANDARD LVCMOS33 } [get_ports {cam_data[2]}]
set_property -dict { PACKAGE_PIN K14 IOSTANDARD LVCMOS33 } [get_ports {cam_data[1]}]
set_property -dict { PACKAGE_PIN J15 IOSTANDARD LVCMOS33 } [get_ports {cam_data[0]}]
set_property -dict { PACKAGE_PIN H16 IOSTANDARD LVCMOS33 } [get_ports {cam_data[7]}]
set_property -dict { PACKAGE_PIN H17 IOSTANDARD LVCMOS33 } [get_ports {cam_data[6]}]
set_property -dict { PACKAGE_PIN K16 IOSTANDARD LVCMOS33 } [get_ports {cam_data[5]}]
set_property -dict { PACKAGE_PIN J16 IOSTANDARD LVCMOS33 } [get_ports {cam_data[4]}]


set_property -dict { PACKAGE_PIN V17 IOSTANDARD TMDS_33 } [get_ports hdmi_tmds_clk_n]
set_property -dict { PACKAGE_PIN U16 IOSTANDARD TMDS_33 } [get_ports hdmi_tmds_clk_p]

set_property -dict { PACKAGE_PIN U18 IOSTANDARD TMDS_33 } [get_ports {hdmi_tmds_data_n[0]}]
set_property -dict { PACKAGE_PIN R17 IOSTANDARD TMDS_33 } [get_ports {hdmi_tmds_data_n[1]}]
set_property -dict { PACKAGE_PIN T14 IOSTANDARD TMDS_33 } [get_ports {hdmi_tmds_data_n[2]}]

set_property -dict { PACKAGE_PIN U17 IOSTANDARD TMDS_33 } [get_ports {hdmi_tmds_data_p[0]}]
set_property -dict { PACKAGE_PIN R16 IOSTANDARD TMDS_33 } [get_ports {hdmi_tmds_data_p[1]}]
set_property -dict { PACKAGE_PIN R14 IOSTANDARD TMDS_33 } [get_ports {hdmi_tmds_data_p[2]}]

set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property BITSTREAM.Config.SPI_buswidth 4 [current_design]




set_property IOSTANDARD LVCMOS33 [get_ports {hex_grid_a[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_grid_a[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_grid_a[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_grid_a[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_grid_b[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_grid_b[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_grid_b[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_grid_b[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_seg_a[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_seg_a[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_seg_a[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_seg_a[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_seg_a[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_seg_a[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_seg_a[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_seg_a[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_seg_b[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_seg_b[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_seg_b[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_seg_b[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_seg_b[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_seg_b[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_seg_b[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_seg_b[0]}]
set_property PACKAGE_PIN G6 [get_ports {hex_grid_a[0]}]
set_property PACKAGE_PIN H6 [get_ports {hex_grid_a[1]}]
set_property PACKAGE_PIN C3 [get_ports {hex_grid_a[2]}]
set_property PACKAGE_PIN B3 [get_ports {hex_grid_a[3]}]
set_property PACKAGE_PIN E6 [get_ports {hex_seg_a[0]}]
set_property PACKAGE_PIN B4 [get_ports {hex_seg_a[1]}]
set_property PACKAGE_PIN D5 [get_ports {hex_seg_a[2]}]
set_property PACKAGE_PIN C5 [get_ports {hex_seg_a[3]}]
set_property PACKAGE_PIN D7 [get_ports {hex_seg_a[4]}]
set_property PACKAGE_PIN D6 [get_ports {hex_seg_a[5]}]
set_property PACKAGE_PIN C4 [get_ports {hex_seg_a[6]}]
set_property PACKAGE_PIN B5 [get_ports {hex_seg_a[7]}]
set_property PACKAGE_PIN F3 [get_ports {hex_seg_b[0]}]
set_property PACKAGE_PIN G5 [get_ports {hex_seg_b[1]}]
set_property PACKAGE_PIN J3 [get_ports {hex_seg_b[2]}]
set_property PACKAGE_PIN H4 [get_ports {hex_seg_b[3]}]
set_property PACKAGE_PIN F4 [get_ports {hex_seg_b[4]}]
set_property PACKAGE_PIN H3 [get_ports {hex_seg_b[5]}]
set_property PACKAGE_PIN E5 [get_ports {hex_seg_b[6]}]
set_property PACKAGE_PIN J4 [get_ports {hex_seg_b[7]}]
set_property PACKAGE_PIN E4 [get_ports {hex_grid_b[0]}]
set_property PACKAGE_PIN E3 [get_ports {hex_grid_b[1]}]
set_property PACKAGE_PIN F5 [get_ports {hex_grid_b[2]}]
set_property PACKAGE_PIN H5 [get_ports {hex_grid_b[3]}]


set_property -dict {PACKAGE_PIN G1 IOSTANDARD LVCMOS33} [get_ports {sw_i[0]}]
set_property -dict {PACKAGE_PIN F2 IOSTANDARD LVCMOS33} [get_ports {sw_i[1]}]
set_property -dict {PACKAGE_PIN F1 IOSTANDARD LVCMOS33} [get_ports {sw_i[2]}]
set_property -dict {PACKAGE_PIN E2 IOSTANDARD LVCMOS33} [get_ports {sw_i[3]}]
set_property -dict {PACKAGE_PIN E1 IOSTANDARD LVCMOS33} [get_ports {sw_i[4]}]
set_property -dict {PACKAGE_PIN D2 IOSTANDARD LVCMOS33} [get_ports {sw_i[5]}]
set_property -dict {PACKAGE_PIN D1 IOSTANDARD LVCMOS33} [get_ports {sw_i[6]}]

set_property -dict {PACKAGE_PIN C2 IOSTANDARD LVCMOS33} [get_ports {sw_i[7]}]
set_property -dict {PACKAGE_PIN B2 IOSTANDARD LVCMOS33} [get_ports {sw_i[8]}]
set_property -dict {PACKAGE_PIN A4 IOSTANDARD LVCMOS33} [get_ports {sw_i[9]}]
set_property -dict {PACKAGE_PIN A5 IOSTANDARD LVCMOS33} [get_ports {sw_i[10]}]
set_property -dict {PACKAGE_PIN A6 IOSTANDARD LVCMOS33} [get_ports {sw_i[11]}]
set_property -dict {PACKAGE_PIN C7 IOSTANDARD LVCMOS33} [get_ports {sw_i[12]}]
set_property -dict {PACKAGE_PIN A7 IOSTANDARD LVCMOS33} [get_ports {sw_i[13]}]
set_property -dict {PACKAGE_PIN B7 IOSTANDARD LVCMOS33} [get_ports {sw_i[14]}]
set_property -dict {PACKAGE_PIN A8 IOSTANDARD LVCMOS33} [get_ports {sw_i[15]}]

