set_property -dict {PACKAGE_PIN N15 IOSTANDARD LVCMOS33} [get_ports clk]
create_clock -period 10.000 [get_ports clk]


set_property IOSTANDARD LVCMOS25 [get_ports {cam_data[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {cam_data[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {cam_data[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {cam_data[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {cam_data[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {cam_data[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {cam_data[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {cam_data[7]}]
set_property PACKAGE_PIN E15 [get_ports {cam_data[7]}]
set_property PACKAGE_PIN H14 [get_ports {cam_data[6]}]
set_property PACKAGE_PIN E14 [get_ports {cam_data[5]}]
set_property PACKAGE_PIN H13 [get_ports {cam_data[4]}]
set_property PACKAGE_PIN J14 [get_ports {cam_data[3]}]
set_property PACKAGE_PIN F15 [get_ports {cam_data[2]}]
set_property PACKAGE_PIN J13 [get_ports {cam_data[1]}]
set_property PACKAGE_PIN F14 [get_ports {cam_data[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports pclk]
set_property IOSTANDARD LVCMOS25 [get_ports cam_href]
set_property IOSTANDARD LVCMOS25 [get_ports cam_vsync]
set_property IOSTANDARD LVCMOS25 [get_ports pwdn]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS25 [get_ports xclk]
set_property IOSTANDARD LVCMOS25 [get_ports reset]
set_property IOSTANDARD LVCMOS25 [get_ports scl]
set_property IOSTANDARD LVCMOS25 [get_ports sda]
set_property IOSTANDARD LVCMOS25 [get_ports start_fsm]
set_property PACKAGE_PIN J16 [get_ports scl]
set_property PACKAGE_PIN J15 [get_ports sda]
set_property PACKAGE_PIN J2 [get_ports start_fsm]
set_property PACKAGE_PIN J1 [get_ports reset]
set_property PACKAGE_PIN H18 [get_ports pwdn]
set_property PACKAGE_PIN G18 [get_ports xclk]
set_property PACKAGE_PIN K16 [get_ports cam_vsync]
set_property PACKAGE_PIN K14 [get_ports cam_href]

set_property PACKAGE_PIN H17 [get_ports pclk]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets pclk_IBUF] 


set_property -dict { PACKAGE_PIN V17   IOSTANDARD TMDS_33 } [get_ports {hdmi_tmds_clk_n}]
set_property -dict { PACKAGE_PIN U16   IOSTANDARD TMDS_33 } [get_ports {hdmi_tmds_clk_p}]

set_property -dict { PACKAGE_PIN U18   IOSTANDARD TMDS_33  } [get_ports {hdmi_tmds_data_n[0]}]
set_property -dict { PACKAGE_PIN R17   IOSTANDARD TMDS_33  } [get_ports {hdmi_tmds_data_n[1]}]
set_property -dict { PACKAGE_PIN T14   IOSTANDARD TMDS_33  } [get_ports {hdmi_tmds_data_n[2]}]
                                    
set_property -dict { PACKAGE_PIN U17   IOSTANDARD TMDS_33  } [get_ports {hdmi_tmds_data_p[0]}]
set_property -dict { PACKAGE_PIN R16   IOSTANDARD TMDS_33  } [get_ports {hdmi_tmds_data_p[1]}]
set_property -dict { PACKAGE_PIN R14   IOSTANDARD TMDS_33  } [get_ports {hdmi_tmds_data_p[2]}]